---
# SERVE | EMAIL-SERVICE CONFIGURATION
serve:
  oauth2:
    resource-id: EmailService
    auth-server-service-id: auth-service
---
spring:
  profiles: local
 
logging:
  level:
    com.giteshdalal: debug
    org.springframework.security: debug
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  profiles: docker

logging:
  level:
    ROOT: error

eureka:
  instance:
    hostname: email
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
