---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# SERVE | PRODUCT-SERVICE CONFIGURATION
serve:
  oauth2:
    resource-id: ProductService
    auth-server-service-id: auth-service

counter:
  prefix-message: 'Testing Counter : '
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/serve?createDatabaseIfNotExist=true&useSSL=false
 
logging:
  level:
    com.giteshdalal: debug
    org.springframework.security: debug
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://db:3306/serve?useSSL=false

logging:
  level:
    ROOT: error

eureka:
  instance:
    hostname: product
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
